// @generated automatically by Diesel CLI.

diesel::table! {
    packages (id) {
        id -> Text,
        attr_path -> Text,
        last_update_attempt -> Nullable<Timestamp>,
        last_update_log -> Nullable<Timestamp>,
        version_nixpkgs_master -> Nullable<Text>,
        last_checked_nixpkgs_master -> Nullable<Timestamp>,
        version_nixpkgs_staging -> Nullable<Text>,
        last_checked_nixpkgs_staging -> Nullable<Timestamp>,
        version_nixpkgs_staging_next -> Nullable<Text>,
        last_checked_nixpkgs_staging_next -> Nullable<Timestamp>,
        version_repology -> Nullable<Text>,
        project_repology -> Nullable<Text>,
        nixpkgs_name_replogy -> Nullable<Text>,
        last_checked_repology -> Nullable<Timestamp>,
        version_github -> Nullable<Text>,
        owner_github -> Nullable<Text>,
        repo_github -> Nullable<Text>,
        last_checked_github -> Nullable<Timestamp>,
        version_gitlab -> Nullable<Text>,
        owner_gitlab -> Nullable<Text>,
        repo_gitlab -> Nullable<Text>,
        last_checked_gitlab -> Nullable<Timestamp>,
        package_name_pypi -> Nullable<Text>,
        version_pypi -> Nullable<Text>,
        last_checked_pypi -> Nullable<Timestamp>,
        pending_pr -> Nullable<Integer>,
        pending_pr_owner -> Nullable<Text>,
        pending_pr_branch_name -> Nullable<Text>,
        last_checked_pending_pr -> Nullable<Timestamp>,
    }
}
